Run gpu build with --gpus flag

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -169,12 +169,28 @@ jobs:
     env:
       BRANCH: ${{ needs.setup.outputs.branch }}
     steps:
+      # This won't actually run the tests, for the Dockerfile_cuda_kokkos
+      # image we need to run the tests in the next step
       - name: Build Docker image with KOKKOS and PETSc with GPU
         uses: docker/build-push-action@v2
         with:
           platforms: linux/amd64
           push: false
           file: ./dockerfiles/Dockerfile_cuda_kokkos
+          # Tag this so we pick it up in the next step
+          tags: pflare/gpu-build:latest
           build-args: |
             BRANCH=${{ env.BRANCH }}
-            ARCH=arch-linux-c-opt             
+            ARCH=arch-linux-c-opt
+
+      # Currently our GPU CI only has a single GPU so we can't run the parallel tests
+      # Check it sees the gpu by running nvidia-smi
+      - name: Run Docker image with explicit --gpus flag
+        run: |
+         docker run --rm --gpus all pflare/gpu-build:latest bash -c "
+         set -e  # Exit immediately if a command fails
+         echo '=== GPU Information ==='
+         nvidia-smi
+         echo '=== Running Tests ==='
+         make tests_serial
+         "
